# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 93b37ffb3e0f1f37d4c59d2ef95b9e23d17a32c6abe08bd604485fcb6bc83c6821fb41c915bc329e18dc9062bde28ef91f79f9795e87c9f8b24a20d643175798

test:
  secret_key_base: e6252ca167955b3e9c060d06eccc960f5bcb1b8b27a444678d9ff63d0df54e0bb6732afaa4d202517b8fcbcd4986ab5f19fad9f54800dcb19ec1ddace2062d78

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: f676c0f7efe7ab423d7b14870e7e943b91bc75dce0adc669f752d3494a382d17f48289fdcbd4dce3d4f460b4eec01dba9aa72abc1e1763a3e5eee3a27eeba204
